=begin
#The Selling Partner API for FBA inbound operations.

#The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.

OpenAPI spec version: 2024-03-20

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.56
=end

# Common files
require 'fulfillment-inbound-api-model/api_client'
require 'fulfillment-inbound-api-model/api_error'
require 'fulfillment-inbound-api-model/version'
require 'fulfillment-inbound-api-model/configuration'

# Models
require 'fulfillment-inbound-api-model/models/address'
require 'fulfillment-inbound-api-model/models/appointment_slot'
require 'fulfillment-inbound-api-model/models/appointment_slot_time'
require 'fulfillment-inbound-api-model/models/box'
require 'fulfillment-inbound-api-model/models/box_content'
require 'fulfillment-inbound-api-model/models/box_content_information_source'
require 'fulfillment-inbound-api-model/models/box_input'
require 'fulfillment-inbound-api-model/models/cancel_inbound_plan_response'
require 'fulfillment-inbound-api-model/models/cancel_self_ship_appointment_request'
require 'fulfillment-inbound-api-model/models/cancel_self_ship_appointment_response'
require 'fulfillment-inbound-api-model/models/carrier'
require 'fulfillment-inbound-api-model/models/compliance_detail'
require 'fulfillment-inbound-api-model/models/confirm_packing_option_response'
require 'fulfillment-inbound-api-model/models/confirm_placement_option_response'
require 'fulfillment-inbound-api-model/models/confirm_transportation_options_request'
require 'fulfillment-inbound-api-model/models/confirm_transportation_options_response'
require 'fulfillment-inbound-api-model/models/contact_information'
require 'fulfillment-inbound-api-model/models/create_inbound_plan_request'
require 'fulfillment-inbound-api-model/models/create_inbound_plan_response'
require 'fulfillment-inbound-api-model/models/currency'
require 'fulfillment-inbound-api-model/models/custom_placement_input'
require 'fulfillment-inbound-api-model/models/dates'
require 'fulfillment-inbound-api-model/models/dimensions'
require 'fulfillment-inbound-api-model/models/document_download'
require 'fulfillment-inbound-api-model/models/error'
require 'fulfillment-inbound-api-model/models/error_list'
require 'fulfillment-inbound-api-model/models/generate_packing_options_response'
require 'fulfillment-inbound-api-model/models/generate_placement_options_request'
require 'fulfillment-inbound-api-model/models/generate_placement_options_response'
require 'fulfillment-inbound-api-model/models/generate_self_ship_appointment_slots_request'
require 'fulfillment-inbound-api-model/models/generate_self_ship_appointment_slots_response'
require 'fulfillment-inbound-api-model/models/generate_transportation_options_request'
require 'fulfillment-inbound-api-model/models/generate_transportation_options_response'
require 'fulfillment-inbound-api-model/models/get_delivery_challan_document_response'
require 'fulfillment-inbound-api-model/models/get_self_ship_appointment_slots_response'
require 'fulfillment-inbound-api-model/models/inbound_operation_status'
require 'fulfillment-inbound-api-model/models/inbound_plan'
require 'fulfillment-inbound-api-model/models/inbound_plan_summary'
require 'fulfillment-inbound-api-model/models/incentive'
require 'fulfillment-inbound-api-model/models/item'
require 'fulfillment-inbound-api-model/models/item_input'
require 'fulfillment-inbound-api-model/models/label_owner'
require 'fulfillment-inbound-api-model/models/list_inbound_plan_boxes_response'
require 'fulfillment-inbound-api-model/models/list_inbound_plan_items_response'
require 'fulfillment-inbound-api-model/models/list_inbound_plan_pallets_response'
require 'fulfillment-inbound-api-model/models/list_inbound_plans_response'
require 'fulfillment-inbound-api-model/models/list_item_compliance_details_response'
require 'fulfillment-inbound-api-model/models/list_packing_group_items_response'
require 'fulfillment-inbound-api-model/models/list_packing_options_response'
require 'fulfillment-inbound-api-model/models/list_placement_options_response'
require 'fulfillment-inbound-api-model/models/list_transportation_options_response'
require 'fulfillment-inbound-api-model/models/ltl_tracking_detail'
require 'fulfillment-inbound-api-model/models/ltl_tracking_detail_input'
require 'fulfillment-inbound-api-model/models/operation_problem'
require 'fulfillment-inbound-api-model/models/operation_status'
require 'fulfillment-inbound-api-model/models/package_grouping_input'
require 'fulfillment-inbound-api-model/models/packing_option'
require 'fulfillment-inbound-api-model/models/packing_option_summary'
require 'fulfillment-inbound-api-model/models/pagination'
require 'fulfillment-inbound-api-model/models/pallet'
require 'fulfillment-inbound-api-model/models/pallet_information'
require 'fulfillment-inbound-api-model/models/pallet_input'
require 'fulfillment-inbound-api-model/models/placement_option'
require 'fulfillment-inbound-api-model/models/placement_option_summary'
require 'fulfillment-inbound-api-model/models/prep_instruction'
require 'fulfillment-inbound-api-model/models/prep_owner'
require 'fulfillment-inbound-api-model/models/quote'
require 'fulfillment-inbound-api-model/models/reason_comment'
require 'fulfillment-inbound-api-model/models/region'
require 'fulfillment-inbound-api-model/models/schedule_self_ship_appointment_request'
require 'fulfillment-inbound-api-model/models/schedule_self_ship_appointment_response'
require 'fulfillment-inbound-api-model/models/self_ship_appointment_details'
require 'fulfillment-inbound-api-model/models/self_ship_appointment_slots_availability'
require 'fulfillment-inbound-api-model/models/set_packing_information_request'
require 'fulfillment-inbound-api-model/models/set_packing_information_response'
require 'fulfillment-inbound-api-model/models/shipment'
require 'fulfillment-inbound-api-model/models/shipment_destination'
require 'fulfillment-inbound-api-model/models/shipment_source'
require 'fulfillment-inbound-api-model/models/shipment_summary'
require 'fulfillment-inbound-api-model/models/shipment_transportation_configuration'
require 'fulfillment-inbound-api-model/models/shipping_configuration'
require 'fulfillment-inbound-api-model/models/spd_tracking_detail'
require 'fulfillment-inbound-api-model/models/spd_tracking_detail_input'
require 'fulfillment-inbound-api-model/models/spd_tracking_item'
require 'fulfillment-inbound-api-model/models/spd_tracking_item_input'
require 'fulfillment-inbound-api-model/models/stackability'
require 'fulfillment-inbound-api-model/models/tax_details'
require 'fulfillment-inbound-api-model/models/tax_rate'
require 'fulfillment-inbound-api-model/models/tracking_details'
require 'fulfillment-inbound-api-model/models/tracking_details_input'
require 'fulfillment-inbound-api-model/models/transportation_option'
require 'fulfillment-inbound-api-model/models/transportation_selection'
require 'fulfillment-inbound-api-model/models/unit_of_measurement'
require 'fulfillment-inbound-api-model/models/unit_of_weight'
require 'fulfillment-inbound-api-model/models/update_item_compliance_details_request'
require 'fulfillment-inbound-api-model/models/update_item_compliance_details_response'
require 'fulfillment-inbound-api-model/models/update_shipment_delivery_window_request'
require 'fulfillment-inbound-api-model/models/update_shipment_delivery_window_response'
require 'fulfillment-inbound-api-model/models/update_shipment_tracking_details_request'
require 'fulfillment-inbound-api-model/models/update_shipment_tracking_details_response'
require 'fulfillment-inbound-api-model/models/weight'
require 'fulfillment-inbound-api-model/models/window'
require 'fulfillment-inbound-api-model/models/window_input'

# APIs
require 'fulfillment-inbound-api-model/api/fba_inbound_api'

module AmzSpApi::FulfillmentInboundApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::FulfillmentInboundApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
