=begin
#Selling Partner API for Orders

#The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools. The Orders API supports orders that are two years old or less. Orders more than two years old will not show in the API response.  **Note:** The Orders API supports orders from 2016 and after for the JP, AU, and SG marketplaces.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.56
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::OrdersApiModel::SubstitutionPreferences
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SubstitutionPreferences' do
  before do
    # run before each test
    @instance = AmzSpApi::OrdersApiModel::SubstitutionPreferences.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubstitutionPreferences' do
    it 'should create an instance of SubstitutionPreferences' do
      expect(@instance).to be_instance_of(AmzSpApi::OrdersApiModel::SubstitutionPreferences)
    end
  end
  describe 'test attribute "substitution_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CUSTOMER_PREFERENCE", "AMAZON_RECOMMENDED", "DO_NOT_SUBSTITUTE"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.substitution_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "substitution_options"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
